index:
    path: /
    controller: App\Controller\HomeController::index

home:
    path: /home
    controller: App\Controller\HomeController::index

trick:
    path: /trick
    controller: App\Controller\TrickController::index
